apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "echo 'hello k8s local storage' > /mnt/SUCCESS && sleep 36000 || exit 1"
    volumeMounts:
    - mountPath: /mnt
      name: example-volume
  volumes:
  - name: example-volume
    persistentVolumeClaim:
      claimName: example-local-claim
